package View;

//NETBEANS
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//PROYECTO
import Model.Planeta;
import Excepcion.PlanetaExcepcion;
import static Controller.Controlador.createplaneta;

/**
 *
 * @author Usuario
 */
public class CrearPlaneta extends javax.swing.JDialog {

    /**
     * Creates new form CrearPlaneta
     */
    public CrearPlaneta(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);

        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imgs/stucom100.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nombreplaneta = new javax.swing.JTextField();
        clima = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nombregalaxia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        poblacionmaxima = new javax.swing.JSpinner();
        flora = new javax.swing.JCheckBox();
        aquatic = new javax.swing.JCheckBox();
        crearplaneta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(0, 67, 188));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setBackground(new java.awt.Color(255, 250, 250));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Flora: ");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, new java.awt.Color(51, 51, 51)));
        jLabel5.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        nombreplaneta.setBackground(new java.awt.Color(255, 250, 250));
        nombreplaneta.setForeground(new java.awt.Color(0, 0, 0));
        nombreplaneta.setPreferredSize(new java.awt.Dimension(73, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 5;
        jPanel2.add(nombreplaneta, gridBagConstraints);

        clima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calido", "Frio", "Templado" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 40);
        jPanel2.add(clima, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(255, 250, 250));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Clima: ");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, new java.awt.Color(51, 51, 51)));
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        nombregalaxia.setBackground(new java.awt.Color(255, 250, 250));
        nombregalaxia.setForeground(new java.awt.Color(0, 0, 0));
        nombregalaxia.setPreferredSize(new java.awt.Dimension(73, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 5;
        jPanel2.add(nombregalaxia, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(255, 250, 250));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Poblacion : ");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, new java.awt.Color(102, 102, 102)));
        jLabel3.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 20);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 250, 250));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Galaxia: ");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, new java.awt.Color(51, 51, 51)));
        jLabel2.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 20);
        jPanel2.add(jLabel2, gridBagConstraints);

        poblacionmaxima.setModel(new javax.swing.SpinnerNumberModel(1, 0, 1000, 1));
        poblacionmaxima.setEditor(new javax.swing.JSpinner.NumberEditor(poblacionmaxima, ""));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 5;
        jPanel2.add(poblacionmaxima, gridBagConstraints);

        flora.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        jPanel2.add(flora, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 40);
        jPanel2.add(aquatic, gridBagConstraints);

        crearplaneta.setText("Crear planeta");
        crearplaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearplanetaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 40);
        jPanel2.add(crearplaneta, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(255, 250, 250));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fauna marina: ");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 250, 250));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Planeta: ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 51, 51), null, new java.awt.Color(51, 51, 51)));
        jLabel1.setFocusable(false);
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 40, 10, 20);
        jPanel2.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 10;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/116713.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("Crear planeta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel3.add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 30;
        getContentPane().add(jPanel3, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botom para crear planeta
     *
     * @param evt
     */
    private void crearplanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearplanetaActionPerformed
        // TODO add your handling code here:

        //Variables de las propiedades de planeta
        String nameplanet = nombreplaneta.getText();
        String namegalaxy = nombregalaxia.getText();
        int maxpopulation = (int) poblacionmaxima.getValue();
        String weather = (String) clima.getSelectedItem();
        boolean floraa = flora.isSelected();
        boolean aquaticc = aquatic.isSelected();

//        Si el nombre planeta no esta vacio o nombre galaxia no esta vacio
        if (!(nameplanet.isEmpty() || namegalaxy.isEmpty())) {
            if (nameplanet.length() <= 3 && namegalaxy.length() <= 3) {
                JOptionPane.showMessageDialog(this, "La longitud del nombre de la galaxia y nombre"
                        + "del planeta no son  correctos (4)",
                        "Nombres incorrectos", JOptionPane.WARNING_MESSAGE);
            } else if (nameplanet.length() <= 3) {
                JOptionPane.showMessageDialog(this, "La longitud del nombre del planeta no es correcto (4)",
                        "Nombre planeta incorrecto", JOptionPane.WARNING_MESSAGE);
            } else if (namegalaxy.length() <= 3) {
                JOptionPane.showMessageDialog(this, "La longitud del nombre de la galaxia no es correcto (4)",
                        "Nombre galaxia incorrecto", JOptionPane.WARNING_MESSAGE);

            } else if (maxpopulation < 0) {
                JOptionPane.showMessageDialog(this, "No se puede introducir numeros negativos",
                        "Numeros negativos", JOptionPane.WARNING_MESSAGE);

            } else {

                //Crear un objeto Planeta con las variables correspondientes
                Planeta p = new Planeta(nameplanet, namegalaxy, maxpopulation, weather, floraa, aquaticc);

                //Try para capturar el error
                try {
                    //Usa la funcion createplaneta
                    createplaneta(p);

                    //Y muestra la siguiente ventana
                    JOptionPane.showMessageDialog(this, "Se ha registrado correctamente el planeta",
                            "Planeta Registrado", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println(p);
                    dispose();
                } catch (PlanetaExcepcion ex) {
                    nombreplaneta.setText("");
                    JOptionPane.showMessageDialog(this, ex.getMessage(),
                            "Planeta No Registrado", JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se puede dejar campos en blanco", "Datos vacíos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_crearplanetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPlaneta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearPlaneta dialog = new CrearPlaneta(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aquatic;
    private javax.swing.JComboBox<String> clima;
    private javax.swing.JButton crearplaneta;
    private javax.swing.JCheckBox flora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombregalaxia;
    private javax.swing.JTextField nombreplaneta;
    private javax.swing.JSpinner poblacionmaxima;
    // End of variables declaration//GEN-END:variables
}
