package View;

public class CrearCiudadano extends javax.swing.JDialog {

    public CrearCiudadano(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        crearhumano = new javax.swing.JButton();
        crearnibiriano = new javax.swing.JButton();
        crearvulcaniano = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        crearandoriano = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        crearklingon = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        crearferengi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/humanoicono.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, -1, -1));

        crearhumano.setBackground(new java.awt.Color(255, 250, 250));
        crearhumano.setForeground(new java.awt.Color(0, 0, 0));
        crearhumano.setText("Humano");
        crearhumano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearhumanoActionPerformed(evt);
            }
        });
        jPanel1.add(crearhumano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, 96, -1));

        crearnibiriano.setBackground(new java.awt.Color(255, 250, 250));
        crearnibiriano.setForeground(new java.awt.Color(0, 0, 0));
        crearnibiriano.setText("Nibiriano");
        crearnibiriano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearnibirianoActionPerformed(evt);
            }
        });
        jPanel1.add(crearnibiriano, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 114, -1, -1));

        crearvulcaniano.setBackground(new java.awt.Color(255, 250, 250));
        crearvulcaniano.setForeground(new java.awt.Color(0, 0, 0));
        crearvulcaniano.setText("Vulcaniano");
        crearvulcaniano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearvulcanianoActionPerformed(evt);
            }
        });
        jPanel1.add(crearvulcaniano, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 114, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/vulcaniano100.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        crearandoriano.setBackground(new java.awt.Color(255, 250, 250));
        crearandoriano.setForeground(new java.awt.Color(0, 0, 0));
        crearandoriano.setText("Andoriano");
        crearandoriano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearandorianoActionPerformed(evt);
            }
        });
        jPanel1.add(crearandoriano, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 275, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/andoriano.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 159, -1, -1));

        crearklingon.setBackground(new java.awt.Color(255, 250, 250));
        crearklingon.setForeground(new java.awt.Color(0, 0, 0));
        crearklingon.setText("Klingon");
        crearklingon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearklingonActionPerformed(evt);
            }
        });
        jPanel1.add(crearklingon, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 275, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/klingon100.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 157, -1, -1));

        crearferengi.setBackground(new java.awt.Color(255, 250, 250));
        crearferengi.setForeground(new java.awt.Color(0, 0, 0));
        crearferengi.setText("Ferengi");
        crearferengi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearferengiActionPerformed(evt);
            }
        });
        jPanel1.add(crearferengi, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 275, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ferengi100.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 159, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * Un boton para abrir la ventana crear Humano
     *
     * @param evt
     */
    private void crearhumanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearhumanoActionPerformed
        // TODO add your handling code here:
        CrearHumano crearhumano = new CrearHumano(new javax.swing.JDialog(), true);
        crearhumano.setLocationRelativeTo(null);
        crearhumano.setVisible(true);

    }//GEN-LAST:event_crearhumanoActionPerformed

    /**
     * Boton para abrir la ventana crear Andoriano
     *
     * @param evt
     */
    private void crearandorianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearandorianoActionPerformed
        // TODO add your handling code here:

        CrearAndoriano crearandoriano = new CrearAndoriano(new javax.swing.JDialog(), true);
        crearandoriano.setLocationRelativeTo(null);
        crearandoriano.setVisible(true);
    }//GEN-LAST:event_crearandorianoActionPerformed

    /**
     * Boton para abrir la ventana crear Ferengi
     *
     * @param evt
     */
    private void crearferengiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearferengiActionPerformed
        // TODO add your handling code here:

        CrearFerengi crearferengi = new CrearFerengi(new javax.swing.JDialog(), true);
        crearferengi.setLocationRelativeTo(null);
        crearferengi.setVisible(true);
    }//GEN-LAST:event_crearferengiActionPerformed

    /**
     * Boton para abrir la ventana crear Klingon
     *
     * @param evt
     */
    private void crearklingonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearklingonActionPerformed
        // TODO add your handling code here:

        CrearKlingon crearklingon = new CrearKlingon(new javax.swing.JDialog(), true);
        crearklingon.setLocationRelativeTo(null);
        crearklingon.setVisible(true);
    }//GEN-LAST:event_crearklingonActionPerformed

    /**
     * Boton para abrir la ventena crear Nibiriano
     *
     * @param evt
     */
    private void crearnibirianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearnibirianoActionPerformed
        // TODO add your handling code here:

        CrearNibiriano crearnibiriano = new CrearNibiriano(new javax.swing.JDialog(), true);
        crearnibiriano.setLocationRelativeTo(null);
        crearnibiriano.setVisible(true);
    }//GEN-LAST:event_crearnibirianoActionPerformed

    /**
     * Boton para abrir la ventana crear Vulcaniano
     *
     * @param evt
     */
    private void crearvulcanianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearvulcanianoActionPerformed
        // TODO add your handling code here:

        CrearVulcaniano crearvulcaniano = new CrearVulcaniano(new javax.swing.JDialog(), true);
        crearvulcaniano.setLocationRelativeTo(null);
        crearvulcaniano.setVisible(true);
    }//GEN-LAST:event_crearvulcanianoActionPerformed

    //===============================================================================================//
    //||                                                                                           ||//
    //===============================================================================================//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCiudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCiudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCiudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCiudadano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearCiudadano dialog = new CrearCiudadano(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearandoriano;
    private javax.swing.JButton crearferengi;
    private javax.swing.JButton crearhumano;
    private javax.swing.JButton crearklingon;
    private javax.swing.JButton crearnibiriano;
    private javax.swing.JButton crearvulcaniano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
